"""hive context - Generate CLAUDE.md for project context."""

from pathlib import Path
from typing import Annotated, Optional

import typer

from hive.core.context import get_context
from hive.core.exceptions import WorkspaceError


def context(
    ctx: typer.Context,
    name: Annotated[
        Optional[str],
        typer.Option("--name", help="Project name."),
    ] = None,
    description: Annotated[
        Optional[str],
        typer.Option("--description", help="Project description."),
    ] = None,
    force: Annotated[
        bool,
        typer.Option("--force", "-f", help="Overwrite existing CLAUDE.md."),
    ] = False,
) -> None:
    """Generate or update CLAUDE.md with project context.

    This file provides context to Claude Code about your project,
    including repos, hive commands, and workflow guidance.

    Run this after 'hive init' or to refresh the context file.
    """
    root = ctx.obj.get("root") if ctx.obj else None
    ctx_obj = get_context(root=root)

    # Check for workspace
    if not ctx_obj.has_workspace():
        typer.secho("Error: workspace.yaml not found. Run 'hive init' first.", fg="red", err=True)
        raise typer.Exit(1)

    try:
        workspace = ctx_obj.load_workspace()
    except WorkspaceError as e:
        typer.secho(f"Error: {e}", fg="red", err=True)
        raise typer.Exit(1)

    claude_md_path = ctx_obj.root / "CLAUDE.md"

    if claude_md_path.exists() and not force:
        typer.secho("CLAUDE.md already exists. Use --force to overwrite.", fg="yellow")
        raise typer.Exit(1)

    # Get project name from flag or directory name
    project_name = name or ctx_obj.root.name

    # Get description
    project_desc = description or "A multi-repo project managed with hive."

    # Build repo dict
    repos = {key: str(repo.path) for key, repo in workspace.repos.items()}

    # Generate content
    _generate_claude_md(claude_md_path, project_name, project_desc, repos)

    typer.secho(f"Generated: {claude_md_path}", fg="green")
    typer.echo("Edit CLAUDE.md to add repo descriptions and project details.")


def _generate_claude_md(
    path: Path,
    project_name: str,
    project_description: str,
    repos: dict[str, str],
) -> None:
    """Generate CLAUDE.md with project context for the planner agent."""
    repo_list = "\n".join(f"- **{key}**: `{rpath}` - [describe what this repo does]" for key, rpath in repos.items())

    content = f'''# {project_name}

{project_description}

## Repositories

This workspace contains the following repositories:

{repo_list}

## Hive Workflow

This project uses **hive** for multi-repo coordination. GitHub Issues are the source of truth.

### Key Commands

```bash
# Planning & Coordination
hive planner              # Open planner session (Claude + interactive menu)
hive pick start           # Interactively select an issue and start working

# Issue Management
hive issue new "title" --repos repo1,repo2   # Create umbrella + repo issues
hive issue list           # List local tasks
hive issue sync <id>      # Sync umbrella issue status

# Working on Tasks
hive start <id>           # Create worktrees and tmux windows for a task
hive start <id> --repos x # Start only specific repos
hive status <id>          # Show task status

# Cleanup
hive clean <id> --yes     # Remove worktrees for a task
```

### Workflow

1. **Plan**: Use `hive planner` to discuss and plan work
2. **Create Issues**: `hive issue new "Feature X" --repos api,web` creates GitHub issues
3. **Start Work**: `hive start <issue_number>` creates worktrees and branches
4. **Implement**: Work in each repo's tmux window, commit and push
5. **Sync**: `hive issue sync <id>` updates the umbrella issue with progress

### Architecture Notes

- **Umbrella Issue**: Created in the hive repo, links to all repo-specific issues
- **Repo Issues**: One per repo, titled "#<umbrella_number>: <title> (<repo>)"
- **Worktrees**: Created in `.hive/wt/<task_id>/<repo>/`
- **Branches**: Named `feat/<task_id>-<repo>`

## Project-Specific Notes

[Add any project-specific context, conventions, or guidelines here]

---
*Generated by hive. Edit this file to add project details.*
'''

    with open(path, "w") as f:
        f.write(content)
